### ISSUE TITLE
Not compileable

### ISSUE THREAD

**Issue by svenluzar** [ftCommunity/ft-TXT#2]
I am using Ubuntu 16.04.3 LTS and I have tried to compile the ft-TXT firmware by the following way:

```
$ wget -O 07-txt-open-source-archiv.zip https://www.fischertechnik.de/-/media/fischertechnik/fite/service/downloads/robotics/txt-controller/documents/07-txt-open-source-archiv.ashx
$ unzip 07-txt-open-source-archiv.zip 
Archive:  07-txt-open-source-archiv.zip
  extracting: 07-TXT-Open Source Archiv/ft-TXT_Build_KE_162.tar.zip 
$ cd 07-TXT-Open\ Source\ Archiv/
$ unzip ft-TXT_Build_KE_162.tar.zip
Archive:  ft-TXT_Build_KE_162.tar.zip
  inflating: ft-TXT_Build_KE_162.tar.gz  
$ tar xvzf ft-TXT_Build_KE_162.tar.gz
$ cd ..
$ git clone git@github.com:ftCommunity/ft-TXT.git
$ cp -r 07-TXT-Open\ Source\ Archiv/ft-TXT/board/knobloch/TXT/rootfs ft-TXT/board/knobloch/TXT
$ cd ft-TXT
$ make
```

After that i got the following error:

```
mkdir -p /home/txtuser/github/ft-TXT/output/target
rsync -a --ignore-times --exclude .svn --exclude .git --exclude .hg --exclude .bzr --exclude CVS \
	--chmod=Du+w --exclude .empty --exclude '*~' \
	/home/txtuser/github/ft-TXT/system/skeleton/ /home/txtuser/github/ft-TXT/output/target/
/usr/bin/install -m 0644 support/misc/target-dir-warning.txt /home/txtuser/github/ft-TXT/output/target/THIS_IS_NOT_YOUR_ROOT_FILESYSTEM
touch /home/txtuser/github/ft-TXT/output/build/.root
/usr/bin/make -j1  HOSTCC="/usr/bin/gcc" HOSTCXX="/usr/bin/g++" silentoldconfig
make[1]: Verzeichnis „/home/txtuser/github/ft-TXT“ wird betreten
mkdir -p /home/txtuser/github/ft-TXT/output/build/buildroot-config/lxdialog
/usr/bin/make CC="/usr/bin/gcc" HOSTCC="/usr/bin/gcc" obj=/home/txtuser/github/ft-TXT/output/build/buildroot-config -C support/kconfig -f Makefile.br conf
make[2]: Verzeichnis „/home/txtuser/github/ft-TXT/support/kconfig“ wird betreten
/usr/bin/gcc -DCURSES_LOC="<ncurses.h>" -DLOCALE  -I/home/txtuser/github/ft-TXT/output/build/buildroot-config -DCONFIG_=\"\"  -MM *.c > /home/txtuser/github/ft-TXT/output/build/buildroot-config/.depend 2>/dev/null || :
/usr/bin/gcc -DCURSES_LOC="<ncurses.h>" -DLOCALE  -I/home/txtuser/github/ft-TXT/output/build/buildroot-config -DCONFIG_=\"\"   -c conf.c -o /home/txtuser/github/ft-TXT/output/build/buildroot-config/conf.o
/usr/bin/gcc -DCURSES_LOC="<ncurses.h>" -DLOCALE  -I/home/txtuser/github/ft-TXT/output/build/buildroot-config -DCONFIG_=\"\"  -I. -c /home/txtuser/github/ft-TXT/output/build/buildroot-config/zconf.tab.c -o /home/txtuser/github/ft-TXT/output/build/buildroot-config/zconf.tab.o
/usr/bin/gcc -DCURSES_LOC="<ncurses.h>" -DLOCALE  -I/home/txtuser/github/ft-TXT/output/build/buildroot-config -DCONFIG_=\"\"   /home/txtuser/github/ft-TXT/output/build/buildroot-config/conf.o /home/txtuser/github/ft-TXT/output/build/buildroot-config/zconf.tab.o  -o /home/txtuser/github/ft-TXT/output/build/buildroot-config/conf
rm /home/txtuser/github/ft-TXT/output/build/buildroot-config/zconf.tab.c
make[2]: Verzeichnis „/home/txtuser/github/ft-TXT/support/kconfig“ wird verlassen
BR2_DEFCONFIG='' KCONFIG_AUTOCONFIG=/home/txtuser/github/ft-TXT/output/build/buildroot-config/auto.conf KCONFIG_AUTOHEADER=/home/txtuser/github/ft-TXT/output/build/buildroot-config/autoconf.h KCONFIG_TRISTATE=/home/txtuser/github/ft-TXT/output/build/buildroot-config/tristate.config BR2_CONFIG=/home/txtuser/github/ft-TXT/.config BR2_EXTERNAL=support/dummy-external /home/txtuser/github/ft-TXT/output/build/buildroot-config/conf --silentoldconfig Config.in
make[1]: Verzeichnis „/home/txtuser/github/ft-TXT“ wird verlassen
>>> toolchain-external undefined Downloading
--2017-12-08 16:50:26--  http://releases.linaro.org/14.05/components/toolchain/binaries/gcc-linaro-arm-linux-gnueabihf-4.9-2014.05_linux.tar.xz
Auflösen des Hostnamen »releases.linaro.org (releases.linaro.org)«... 64.28.99.46
Verbindungsaufbau zu releases.linaro.org (releases.linaro.org)|64.28.99.46|:80... verbunden.
HTTP-Anforderung gesendet, warte auf Antwort... 404 NOT FOUND
2017-12-08 16:50:27 FEHLER 404: NOT FOUND.

--2017-12-08 16:50:27--  http://sources.buildroot.net/gcc-linaro-arm-linux-gnueabihf-4.9-2014.05_linux.tar.xz
Auflösen des Hostnamen »sources.buildroot.net (sources.buildroot.net)«... 176.9.16.109
Verbindungsaufbau zu sources.buildroot.net (sources.buildroot.net)|176.9.16.109|:80... verbunden.
HTTP-Anforderung gesendet, warte auf Antwort... 404 Not Found
2017-12-08 16:50:27 FEHLER 404: Not Found.

package/pkg-generic.mk:73: die Regel für Ziel „/home/txtuser/github/ft-TXT/output/build/toolchain-external-undefined/.stamp_downloaded“ scheiterte
make: *** [/home/txtuser/github/ft-TXT/output/build/toolchain-external-undefined/.stamp_downloaded] Fehler 1
```
The buildroot resources are no longer available. Do you have got any suggestion how I can build this firmware?

**Comment by rkunze** [comment]
No, not really. And no plans to fix it, either - this repository is mainly here to preserve the original firmware sources released by Fischertechnik, in case they vanish from www.fischertechnik.de

If you want a free firmware for your TXT, head over to https://github.com/ftCommunity/ftcommunity-TXT - that's where the real development happens.

**Comment by svenluzar** [comment]
I agree that the community firmware is much more powerful than the original firmware. On the other hand, the community firmware requires an additional SD card. I would like to know if it is possible to compile the original firmware with Python 2.7 and how much space this new operating system would need? Would it be possible to store the new operation system on the internal flash card?

Hence I tried to upgrade this repository with a newer version of buildroot. I cloned a newer version of buildroot, copied the sources from board/knobloch into it and with some small issues i could compile the complete package. After that i copied everything on an SD card (only for testing) and started the new operating system. Everything looked ok, but the controller hangs after the console output _Starting kernel ..._. Do you have any hints for me, how i can solve or debug this situation?

```
Could not probe the EEPROM; something fundamentally wrong on the I2C bus.
Could not get board ID.
Net:   usb_ether

NAND read: device 0 offset 0x700000, size 0x40000
 262144 bytes read: OK
CopyToLcd
LCD Command called
Hit ENTER key to stop autoboot:  0
gpio: pin 97 (gpio 97) value is 0
gpio: pin 98 (gpio 98) value is 0

NAND read: device 0 offset 0x200000, size 0x500000
 5242880 bytes read: OK

NAND read: device 0 offset 0x80000, size 0x40000
 262144 bytes read: OK
reading uImage
5351512 bytes read in 355 ms (14.4 MiB/s)
reading am335x-kno_txt.dtb
35916 bytes read in 7 ms (4.9 MiB/s)
## Booting kernel from Legacy Image at 80200000 ...
   Image Name:   Linux-4.9.13
   Image Type:   ARM Linux Kernel Image (uncompressed)
   Data Size:    5351448 Bytes = 5.1 MiB
   Load Address: 80008000
   Entry Point:  80008000
   Verifying Checksum ... OK
## Flattened Device Tree blob at 80f00000
   Booting using the fdt blob at 0x80f00000
   Loading Kernel Image ... OK
   Loading Device Tree to 8f309000, end 8f314c4b ... OK

Starting kernel ...
```

**Comment by rkunze** [comment]
> I agree that the community firmware is much more powerful than the original firmware. On the other hand, the community firmware requires an additional SD card.

That was a design decision. By using an SD card for the community firmware, we need almost no modifcations to the original setup of the TXT. We just need to reconfigure u-boot to boot from SD card first and then from internal flash, instead of from internal flash only as in the original setting - and this reconfiguration has the "official blessing" from fischertechnik since the release of RoboPro 2.4.2 and its associated original firmware (see here for details: https://www.fischertechnik.de/-/media/fischertechnik/fite/service/downloads/robotics/txt-controller/documents/activation_bootloaders_english.ashx). 

After doing that, we can switch back and forth between CFW and the original firmware simply by inserting/removing the SD card.

> Hence I tried to upgrade this repository with a newer version of buildroot.

That's basically what we did as well. The result (plus a bit of extra bundled software such as Python 3, Qt 4.8, OpenCV and a bit of "homegrown" stuff mostly written in Python) is the community firmware.

> I would like to know if it is possible to compile the original firmware with Python 2.7 and how much space this new operating system would need? Would it be possible to store the new operation system on the internal flash card?

If you just want Python 2.7 for the original firmware, here's a precompiled bundle: http://ftcommunity.de/data/downloads/software/python_for_fttxt.zip

If you want to cross-compile your own C software for the TXT, you can probably use the CFW buildroot as a cross-compile environment for the original firmware. Should work out of the box for statically linked binaries, and probably will work for dynamically linked binaries as well (maybe you need to copy over the newer libc and other standard libraries, though, since CFW is based on a newer buildroot version than the original firmware).

If you want an easy way to build binaries for the TXT (either CFW or original firmware) in a modern language, you might give go (https://golang.org/) a try. Crosscompiling for the TXT is dead easy (just set GOARCH=arm and GOOS=linux in any recent go installation), and go produces static binaries by default so you can just copy over the resulting binary (only drawback: go binaries tend to get quite large because of the included runtime).

And if you absolutely want to, the CFW should fit into the internal flash: Internal flash on the TXT is 128MB (yes, it's double the size fischertechnik claims on the product page. Same for the RAM, btw., that is 256MB instead of 128MB as claimed by fischertechnik), and the current CFW install is around 90MB (a bit less than 85MB for the Squashfs root image, and around 6MB kernel) - a bit tight, but should work (and even leave a couple MB for a writeable overlay). Although I would not recommend such a setup: There's no easy way back to the original firmware, it would require quite a bit of fiddling with the CFW, and reflashing for every CFW update would put a lot of write stress on the internal flash. And frankly, I don't really see a benefit over the standard setup with the CFW on an external SD card.

And finally, here's a great resource for everything related to fischertechnik, and the place where most all of the CFW devs hang out as well: http://forum.ftcommunity.de/ (forum language is predominantly German, but don't hesitate to post in English).

**Comment by svenluzar** [comment]
Thanks for all the interesting information. I will try the different approaches.
